#!/usr/bin/env bash

# Copyright 2023 EdgeBit, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and

SCOPE_PREFIX='^.+: '
TITLE_LENGTH=50
LINE_LENGTH=70

commit_msg=$(< $1)
commit_title=$(head -n1 <<< "${commit_msg}")

die() {
    echo "Improperly formatted commit message (${1}). Please use the following form:"
    echo "    <scope>: <title>"
    echo
    echo "    <description>"
    echo "See the README for more information."
    exit 1
}

[[ "${commit_title}" =~ $SCOPE_PREFIX ]] || die "missing scope"
(( ${#commit_title} < $TITLE_LENGTH )) || die "title too long"

num=0
while read line
do
    ((num++))
    [[ "${line}" == \#* ]] && continue
    (( ${#line} <= LINE_LENGTH )) || die "line ${num} too long"
done <<< "${commit_msg}"
